// <auto-generated />
using MassTransitAllog.Producer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MassTransitAllog.Producer.Migrations
{
    [DbContext(typeof(ClienteContext))]
    [Migration("20230804194859_InitialMigration3")]
    partial class InitialMigration3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MassTransitAllog.Producer.Entities.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cidades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Itajaí",
                            UF = "SC"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Navegantes",
                            UF = "SC"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "São Paulo",
                            UF = "SP"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Rio de Janeiro",
                            UF = "RJ"
                        });
                });

            modelBuilder.Entity("MassTransitAllog.Producer.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id_cidade")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id_cidade");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Endereco = "Rua Etc Bairro Teste Numero 121",
                            Id_cidade = 2,
                            Nome = "Paulo",
                            Telefone = "123679677"
                        },
                        new
                        {
                            Id = 2,
                            Endereco = "Rua Etc Bairro Teste Numero 121",
                            Id_cidade = 2,
                            Nome = "Carlos",
                            Telefone = "123679677"
                        },
                        new
                        {
                            Id = 3,
                            Endereco = "Rua Etc Bairro Teste Numero 121",
                            Id_cidade = 2,
                            Nome = "Saulo",
                            Telefone = "123679677"
                        },
                        new
                        {
                            Id = 4,
                            Endereco = "Rua Etc Bairro Teste Numero 121",
                            Id_cidade = 1,
                            Nome = "Marco",
                            Telefone = "123679677"
                        },
                        new
                        {
                            Id = 5,
                            Endereco = "Rua Etc Bairro Teste Numero 121",
                            Id_cidade = 1,
                            Nome = "João",
                            Telefone = "123679677"
                        },
                        new
                        {
                            Id = 6,
                            Endereco = "Rua Etc Bairro Teste Numero 121",
                            Id_cidade = 3,
                            Nome = "Pedro",
                            Telefone = "123679677"
                        },
                        new
                        {
                            Id = 7,
                            Endereco = "Rua Etc Bairro Teste Numero 121",
                            Id_cidade = 4,
                            Nome = "Luís",
                            Telefone = "123679677"
                        },
                        new
                        {
                            Id = 8,
                            Endereco = "Rua Etc Bairro Teste Numero 121",
                            Id_cidade = 4,
                            Nome = "Guilherme",
                            Telefone = "123679677"
                        },
                        new
                        {
                            Id = 9,
                            Endereco = "Rua Etc Bairro Teste Numero 121",
                            Id_cidade = 4,
                            Nome = "Pedro",
                            Telefone = "123679677"
                        },
                        new
                        {
                            Id = 10,
                            Endereco = "Rua Etc Bairro Teste Numero 121",
                            Id_cidade = 4,
                            Nome = "Jorge",
                            Telefone = "123679677"
                        },
                        new
                        {
                            Id = 11,
                            Endereco = "Rua Etc Bairro Teste Numero 121",
                            Id_cidade = 4,
                            Nome = "Matheus",
                            Telefone = "123679677"
                        },
                        new
                        {
                            Id = 12,
                            Endereco = "Rua Etc Bairro Teste Numero 121",
                            Id_cidade = 4,
                            Nome = "Guilherme Rosa",
                            Telefone = "123679677"
                        },
                        new
                        {
                            Id = 13,
                            Endereco = "Rua Etc Bairro Teste Numero 121",
                            Id_cidade = 4,
                            Nome = "Lucas Iago",
                            Telefone = "123679677"
                        },
                        new
                        {
                            Id = 14,
                            Endereco = "Rua Etc Bairro Teste Numero 121",
                            Id_cidade = 4,
                            Nome = "Thomas Shelby",
                            Telefone = "123679677"
                        },
                        new
                        {
                            Id = 15,
                            Endereco = "Rua Etc Bairro Teste Numero 121",
                            Id_cidade = 4,
                            Nome = "Superman",
                            Telefone = "123679677"
                        },
                        new
                        {
                            Id = 16,
                            Endereco = "Rua Etc Bairro Teste Numero 121",
                            Id_cidade = 4,
                            Nome = "Batman",
                            Telefone = "123679677"
                        },
                        new
                        {
                            Id = 17,
                            Endereco = "Rua Etc Bairro Teste Numero 121",
                            Id_cidade = 4,
                            Nome = "Flash",
                            Telefone = "234567899"
                        });
                });

            modelBuilder.Entity("MassTransitAllog.Producer.Entities.Cliente", b =>
                {
                    b.HasOne("MassTransitAllog.Producer.Entities.Cidade", "Cidade")
                        .WithMany("Clientes")
                        .HasForeignKey("Id_cidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("MassTransitAllog.Producer.Entities.Cidade", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
